### ISSUE TITLE
Risk of broken links between license and governance documents.

### ISSUE THREAD

**Issue by aquabu** [aquabu/peer-production-royalty-token-license#16]
Can we reduce the risk of broken references between docs by merging the license and governance agreement? Or is it better to keep them separate with URL references between them?

**Comment by jesseposner** [comment]
The core contributors' rights to modify the license agreement need to be limited and carefully defined because they don't require the consent of the contributors or users, whereas, the rights to modify the governance agreement can be more flexible because it is agreement solely among the core contributors. Separate agreements underscore this distinction, and merging the agreements while retaining the distinction could be unwieldy.
